development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: knowledgestream_development
  pool: 5
  username: root
  password: root
  socket: /run/mysqld/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: knowledgestream_test
  pool: 5
  username: root
  password: root
  socket: /run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: knowledgestream_production
  pool: 5
  username: root
  password: root
  socket: /run/mysqld/mysqld.sock
